name: Build and Push Poller Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API
        run: |
          source .venv/bin/activate
          TEST_MODE=true uvicorn src.api.main:app --host 127.0.0.1 --port 8000 &

      - name: Wait for API
        run: |
          sleep 5

      - name: Run tests
        env:
          TEST_MODE: true
        run: |
          source .venv/bin/activate
          pytest

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name marketmlacr123

      - name: Build Docker image
        run: |
          docker build \
            -t marketmlacr123.azurecr.io/poller-service:latest \
            -f docker/Dockerfile.poller .

      - name: Push Docker image
        run: |
          docker push marketmlacr123.azurecr.io/poller-service:latest